"""add error message field to live data

Revision ID: 0c9a1f2202d4
Revises: 56c4f4b619ca
Create Date: 2025-07-29 07:56:13.094720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c9a1f2202d4'
down_revision: Union[str, Sequence[str], None] = '56c4f4b619ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livedata', sa.Column('err', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('livedata', 'err')
    # ### end Alembic commands ###
