"""Initial schema

Revision ID: 50ecca511334
Revises: 
Create Date: 2025-07-10 13:15:48.681137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ecca511334'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('battery_returned', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rental', sa.Column('battery_return_condition', sa.String(length=50), nullable=True))
    op.add_column('rental', sa.Column('battery_return_notes', sa.Text(), nullable=True))
    op.add_column('rental', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'status')
    op.drop_column('rental', 'battery_return_notes')
    op.drop_column('rental', 'battery_return_condition')
    op.drop_column('rental', 'battery_returned')
    # ### end Alembic commands ###
