"""Initial migration from current models

Revision ID: 9319d9f864f9
Revises: 
Create Date: 2025-07-11 11:18:05.261859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9319d9f864f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the enum type if it doesn't exist
    pueusagelocation = sa.Enum('HUB_ONLY', 'BATTERY_ONLY', 'BOTH', name='pueusagelocation')
    pueusagelocation.create(op.get_bind(), checkfirst=True)
    
    # First update the data to match enum values
    op.execute("UPDATE productiveuseequipment SET usage_location = 'HUB_ONLY' WHERE usage_location = 'hub_only'")
    op.execute("UPDATE productiveuseequipment SET usage_location = 'BATTERY_ONLY' WHERE usage_location = 'battery_only'")
    
    # Convert column with proper casting
    op.alter_column('productiveuseequipment', 'usage_location',
               existing_type=sa.VARCHAR(length=50),
               type_=pueusagelocation,
               existing_nullable=True,
               postgresql_using='usage_location::pueusagelocation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('productiveuseequipment', 'usage_location',
               existing_type=sa.Enum('HUB_ONLY', 'BATTERY_ONLY', 'BOTH', name='pueusagelocation'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    
    # Drop the enum type
    sa.Enum(name='pueusagelocation').drop(op.get_bind())
    # ### end Alembic commands ###
